# Generated by Django 4.0.5 on 2022-06-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url_name',
            field=models.CharField(max_length=5000),
        ),
    ]
